name: trigger_test
on:  
  repository_dispatch:
    types: [trigger-pipeline]
jobs:
  testing_trigger_event:
    name: testing-trigger
    runs-on: self-hosted
      run echo "test trigger"
    
                 



